-- Sequence

CREATE SEQUENCE IF NOT EXISTS public.balace_user_id_seq
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 1;

ALTER SEQUENCE public.balace_user_id_seq
    OWNER TO postgres;

CREATE SEQUENCE IF NOT EXISTS public.banner_id_seq
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 1;

ALTER SEQUENCE public.banner_id_seq
    OWNER TO postgres;

CREATE SEQUENCE IF NOT EXISTS public.history_transaction_id_seq
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 1;

ALTER SEQUENCE public.history_transaction_id_seq
    OWNER TO postgres;

CREATE SEQUENCE IF NOT EXISTS public.service_provide_id_seq
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 1;

ALTER SEQUENCE public.service_provide_id_seq
    OWNER TO postgres;

-- Tabel
CREATE TABLE IF NOT EXISTS public.balance_user
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    balance numeric(38,2),
    user_id bigint,
    CONSTRAINT balace_user_pkey PRIMARY KEY (id),
    CONSTRAINT uk4auvvvy6b0yyk48s0xohemlyn UNIQUE (user_id),
    CONSTRAINT ukj0obixm4aiu0ry1ryb6gbrvtx UNIQUE (user_id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.balance_user
    OWNER to postgres;

CREATE TABLE IF NOT EXISTS public.banner
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    information character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    url_image character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT banner_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.banner
    OWNER to postgres;

CREATE TABLE IF NOT EXISTS public.history_transaction
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    date_transaction timestamp(6) without time zone,
    service_provide_id bigint,
    total_amount numeric(38,2),
    transaction_type character varying(255) COLLATE pg_catalog."default",
    user_id bigint,
    CONSTRAINT history_transaction_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.history_transaction
    OWNER to postgres;

CREATE TABLE IF NOT EXISTS public.service_provide
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    active boolean,
    code character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    price numeric(38,2),
    url_icon character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT service_provide_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.service_provide
    OWNER to postgres;